apiVersion: v1
kind: ConfigMap
metadata:
  name: automation-platform-config
  namespace: automation-platform
data:
  # Database Configuration
  DATABASE_URL: "postgresql://postgres:password@postgres-service:5432/automation_platform"
  REDIS_URL: "redis://redis-service:6379"
  MONGODB_URL: "mongodb://mongodb-service:27017/analytics"
  
  # Application Configuration
  NODE_ENV: "production"
  LOG_LEVEL: "info"
  API_URL: "https://api.automation-platform.com"
  FRONTEND_URL: "https://automation-platform.com"
  
  # Feature Flags
  ENABLE_AI_FEATURES: "true"
  ENABLE_ANALYTICS: "true"
  ENABLE_NOTIFICATIONS: "true"
  ENABLE_AUDIT_LOGGING: "true"
  
  # Rate Limiting
  RATE_LIMIT_WINDOW_MS: "900000"
  RATE_LIMIT_MAX_REQUESTS: "100"
  
  # Service Ports
  AUTH_SERVICE_PORT: "3001"
  WORKFLOW_SERVICE_PORT: "3002"
  INTEGRATION_SERVICE_PORT: "3003"
  AI_SERVICE_PORT: "3004"
  ANALYTICS_SERVICE_PORT: "3005"
  NOTIFICATION_SERVICE_PORT: "3006" 